Feature/api
JainishaParmar/NodeJs-tutorial pull request #19
Opened 2021-12-21 05:34 UTC by JainishaParmar

created APIs

2021-12-21 05:36 UTC, jaimin45 approved these changes

2021-12-21 05:55 UTC, kapilbarad requested changes
@jaimin45 @ashishkava Please apply the same suggested changes in your code.

2021-12-21 05:55 UTC, kapilbarad commented on .eslintrc.json
> +    "new-cap":"off",
We should not disable any rules. Remove this newly added rules.

2021-12-21 05:55 UTC, kapilbarad commented on app.js
> +// eslint-disable-next-line no-console
No need of this line here `// eslint-disable-next-line no-console`.

2021-12-21 05:55 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +  try {
We should return a proper success or error response based on Swagger API Design here.

2021-12-21 05:55 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +    console.log(result);
We should return newly created tutorial in response.

2021-12-21 05:55 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +    console.log(err);
We should return a proper error response.

2021-12-21 05:55 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +    res.json(tutorials);
1. This API should only return a single Tutorial.
2. If the given tutorial ID doesn't exist in the database then it should return a proper response with `404` response code.

2021-12-21 05:55 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +    console.log("error");
We should return a proper error response from here.

2021-12-21 05:55 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +    console.log(updateData);
We should return proper response here base don API design.

2021-12-21 05:55 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +  const tutorial = await getUpdateTutorial(data);
We should just update the tutorial here , no need to define another function for that.

2021-12-21 05:55 UTC, kapilbarad commented on models/tutorial.schema.js
> +  id: {
ID is autogenerated in  mongoose no need to define it here.

2021-12-21 05:55 UTC, kapilbarad commented on models/tutorial.schema.js
> +  createdAt: {
`createdAt` and `updatedAt` can be autogenerated using some options. Please follow this docs - https://masteringjs.io/tutorials/mongoose/timestamps

2021-12-21 05:55 UTC, kapilbarad commented on routes/tutorial.routes.js
> +router.get("/getTutorial", getTutorial);
Please use same paths for APIs as specified in the swagger.

2021-12-21 05:56 UTC, kapilbarad commented
@JainishaParmar Please pull latest in develop before starting any new feature. Otherwise you'll see conflicts in code.

2021-12-21 07:27 UTC, ashishkava approved these changes

2021-12-21 07:54 UTC, jaimin45 approved these changes

2021-12-21 10:27 UTC, kapilbarad requested changes
1. path in swagger should be `/tutorials`
2. Add missing api in swagger `GET /tutorials/:id`
3. Add missing responses of the APIs in swaager
```
GET /tutorials/:id
   200: When tutorial exists
   404: When tutorial doesn't exist
   
```

2021-12-21 10:27 UTC, kapilbarad commented on models/tutorial.schema.js
> +  // eslint-disable-next-line spellcheck/spell-checker
Please shift this to spellchecker ignore file.

2021-12-21 10:27 UTC, kapilbarad commented on models/tutorial.schema.js
> +    published: {
Missing title, description fields in schema and swagger

2021-12-21 10:27 UTC, kapilbarad commented on routes/tutorial.routes.js
> +router.delete("/:tutorialId", deleteTutorials);
We should follow proper naming conventions. The `tutorialId` can be just `id`.

2021-12-21 10:27 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +    res.status(400).send(error);
- Log the error
- Should be 500 response with `{ message: 'Internal Server Error' }`.

2021-12-21 10:27 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +    res.send(savedTutorial);
You can send `tutorial`.

2021-12-21 10:27 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +  try {
```
const { title, description } = req.body
const update = {}
if (typeof title !== 'undefined') update.title = title
if (typeof description !== 'undefined') update.description = description
```

2021-12-21 10:27 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +    res.json(tutorialUpdate);
Patch request should always return `204` - No Content.
```
res.status(204).send()
```

2021-12-21 10:27 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +    const tutorials = await Tutorial.findById(req.params.tutorialId);
Should be just `tutorial = `

2021-12-21 10:27 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +    res.json(tutorials);
Should return 404 when tutorial doesn't exist.
```
if (!tutorial) return res.status(404).send({message: 'Tutorial not found'})
```

2021-12-21 10:27 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +    res.json(tutorialRemove);
No need to return anything on delete.
```
res.status(204).send()
```

2021-12-22 05:09 UTC, kapilbarad requested changes

2021-12-22 05:09 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +    res.json(tutorialRemove);
We're sending response two times here. Plz correct this.

2021-12-22 05:09 UTC, kapilbarad commented on routes/tutorial.routes.js
> +/* GET users listing. */
Please remove this unnecessary comment.

2021-12-22 05:09 UTC, kapilbarad commented on routes/tutorial.routes.js
> +router.get("/:Id", getTutorialById);
`Id` should be `id`

2021-12-22 05:09 UTC, kapilbarad commented on swagger.yaml
>        - name: id
No need of parameters here as we're not using it in PATH anywhere.

2021-12-22 05:09 UTC, kapilbarad commented on swagger.yaml
> +        - name: title
Why title? Please test and correct this. You can test it from swagger UI and see how it's passing data to body.

2021-12-22 05:09 UTC, kapilbarad commented on swagger.yaml
> +      title:
Please specify required fields.

2021-12-22 07:38 UTC, jaimin45 approved these changes

2021-12-22 09:56 UTC, ashishkava approved these changes

2021-12-23 05:05 UTC, jaimin45 requested changes

2021-12-23 05:05 UTC, jaimin45 commented on models/tutorial.schema.js
> +  // eslint-disable-next-line spellcheck/spell-checker
remove this spell check line

2021-12-23 05:09 UTC, jaimin45 approved these changes

2021-12-23 08:42 UTC, ashishkava approved these changes

2021-12-23 13:42 UTC, kapilbarad approved these changes

2021-12-24 11:58 UTC, ashishkava approved these changes

2021-12-27 04:51 UTC, jaimin45 approved these changes

2021-12-27 04:51 UTC, ashishkava approved these changes

2021-12-27 05:29 UTC, JainishaParmar commented
feature/api

2021-12-27 05:30 UTC, merged