Feature/validation joi
JainishaParmar/NodeJs-tutorial pull request #21
Opened 2021-12-27 09:47 UTC by JainishaParmar

added Joi validations

2021-12-27 11:12 UTC, jaimin45 approved these changes

2021-12-28 05:30 UTC, jaimin45 approved these changes

2021-12-28 11:02 UTC, jaimin45 approved these changes

2021-12-29 04:39 UTC, kapilbarad requested changes

2021-12-29 04:39 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +    res.status(500).send({ message: "Tutorial not found" });
The error should be internal server error because we don't know what's the error.

2021-12-29 04:39 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +      res.status(400).send({ message: "Invalid Tutorial details" });
Please check my comments in @jaimin45 's PR.

2021-12-29 04:39 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +      res.status(404).send({ message: "Not Found Tutorial" });
Please correct the error message `Tutorial not found`

2021-12-29 11:30 UTC, jaimin45 approved these changes

2021-12-29 11:32 UTC, ashishkava approved these changes

2021-12-29 11:57 UTC, kapilbarad approved these changes

2021-12-29 12:02 UTC, JainishaParmar commented
feature/validationJoi

2021-12-29 12:03 UTC, merged