docs:winston logger added
JainishaParmar/NodeJs-tutorial pull request #22
Opened 2021-12-30 07:06 UTC by JainishaParmar

added winston logger

2021-12-30 07:08 UTC, jaimin45 approved these changes

2021-12-30 07:33 UTC, jaimin45 approved these changes

2021-12-30 08:16 UTC, kapilbarad requested changes

2021-12-30 08:16 UTC, kapilbarad commented on app.js
> +if (promise) {
This is not how a promise works. Please read this docs:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

CC: @ashishkava @jaimin45

2021-12-30 08:16 UTC, kapilbarad commented on app.js
> +const tutorialWinston = require("./config/tutorial.winston");
We don't need to define loggers based on modules.

There will be only one logger `./config/logger`, Which should export a logger instance by default.
So we can use it like this:

```
logger.info('Something....');
```

CC: @jaimin45 @ashishkava

2021-12-30 08:16 UTC, kapilbarad commented on config/tutorial.winston.js
> +module.exports = { tutorialLogger };
We should export logger as default. Also name of the variable should be `logger`.

2021-12-30 08:16 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +      logger.tutorialLogger.log('error', 'Tutorial not found');
We only need to log 500 (any 5xx errors) errors. No need to log 400, 404, or any other 4xx errors.

CC: @jaimin45 @ashishkava

2021-12-30 08:16 UTC, kapilbarad commented on package.json
> +    "app-root-path": "^3.0.0",
What is the need of this dependency - `app-root-path`?

2021-12-30 10:27 UTC, jaimin45 approved these changes

2021-12-30 12:21 UTC, ashishkava approved these changes

2021-12-31 03:33 UTC, kapilbarad requested changes

2021-12-31 03:33 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +      logger.error('Internal Server Error');
We also need to log actual error, otherwise how would we know that what was the root cause of this 500?

2021-12-31 03:33 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +      logger.error('Internal Server Error');
You can configure this method to print errors:

```
const winston = require('winston');
const { format } = require('logform');

const logger = winston.createLogger({
  format: format.combine(
    format.errors({ stack: true }),
    format.metadata(),
    format.json(),
  ),
  transports: [ new winston.transports.Console() ],
});
```
Now you can log errors like this:
```
logger.error(error);
```


For above code to work, You need to install `logform` dependency.

CC: @jaimin45 @JainishaParmar @ashishkava

2021-12-31 04:45 UTC, jaimin45 approved these changes

2021-12-31 05:56 UTC, kapilbarad requested changes

2021-12-31 05:56 UTC, kapilbarad commented on controllers/tutorial.controller.js
> +    logger.error('Internal server error', error);
Error name should be something we can easily track: `('Couldn't fetch tutorials: ', error)`

2021-12-31 06:07 UTC, JainishaParmar commented
feat: winston logger

2021-12-31 06:08 UTC, JainishaParmar commented
feat: winston logger

2021-12-31 06:08 UTC, merged