feat:added environment variables
JainishaParmar/NodeJs-tutorial pull request #23
Opened 2021-12-31 08:44 UTC by JainishaParmar

added Envs

2021-12-31 09:19 UTC, jaimin45 approved these changes

2021-12-31 09:27 UTC, kapilbarad requested changes
- Please update Readme to add section which will explain envs.
- Add .env in .gitignore

2021-12-31 09:27 UTC, ashishkava approved these changes

2022-01-03 04:20 UTC, kapilbarad requested changes

2022-01-03 04:20 UTC, kapilbarad commented on README.md
> +```sh
Here, you should explain to set required environment variables, Make sure to not expose any real secrets you can still use local host URL and all.
```
MONGO_URL="mongodb://localhost:27017/tutorials"
```

2022-01-03 07:16 UTC, jaimin45 approved these changes

2022-01-03 07:19 UTC, ashishkava approved these changes

2022-01-03 07:31 UTC, JainishaParmar commented
feat:set ENVs

2022-01-03 07:31 UTC, merged