feat:APIs for user authentication
JainishaParmar/NodeJs-tutorial pull request #24
Opened 2022-01-03 10:12 UTC by JainishaParmar

added APIs for authentication

2022-01-04 05:00 UTC, jaimin45 approved these changes

2022-01-04 12:34 UTC, jaimin45 approved these changes

2022-01-04 12:36 UTC, ashishkava approved these changes

2022-01-05 09:20 UTC, jaimin45 approved these changes

2022-01-05 09:26 UTC, kapilbarad requested changes

2022-01-05 09:26 UTC, kapilbarad commented on swagger.yaml
> +        description: Tutorial id
Need to correct description.

2022-01-05 09:26 UTC, kapilbarad commented on swagger.yaml
> +          description: 'User is unauthorized'
Just `Unauthorized` would be fine.

2022-01-05 09:26 UTC, kapilbarad commented on swagger.yaml
> +  /oauth/reset-password:
We need 401 response for this API, so we can return Unauthorized when provided invalid expired JWT token.

2022-01-05 09:26 UTC, kapilbarad commented on swagger.yaml
> +            $ref: '#/definitions/OauthLogin'
Should be PostOauthTokenBody

2022-01-05 09:53 UTC, kapilbarad approved these changes

2022-01-05 10:10 UTC, JainishaParmar commented
feat:APIs for user Authentication

2022-01-05 10:10 UTC, merged